// Textes visibles de la page du copilote (06/10/2026, publication sur GitHub) : en français, la langue d'Ameur et le défaut, et
// en anglais. Un seul dictionnaire, lu par overlay.js et par essais/essai-page.mjs (mêmes clés dans les deux langues, et les
// textes français d'index.html doivent être ceux d'ici : la page s'affiche en français avant même que ce fichier soit lu).
// Dans index.html : data-t (texte), data-t-title (info-bulle), data-t-aria (aria-label) donnent la clé.
'use strict';
self.TEXTES_COPILOTE = {
  fr: {
    nom: 'Copilote CK3',
    panneau: 'Réponse du copilote',
    attente: 'Je regarde ton écran…',
    sources: 'Sources',
    suggestions: 'Suggestions de recherche Google',
    deplacer: 'Fais glisser le panneau pour le déplacer : il restera à cet endroit · clic droit : replier, recharger ou quitter',
    pret: 'Prêt',
    repeter: 'Répéter la voix',
    voix: 'Voix',
    voixOn: 'Voix activée (cliquer pour couper)',
    voixOff: 'Voix coupée (cliquer pour l\'activer)',
    nouvelle: 'Nouvelle question',
    reduireInfo: 'Réduire (la réponse est gardée : clic sur l\'icône pour la rouvrir)',
    reduire: 'Réduire en gardant la réponse',
    fermer: 'Fermer',
    // Raccourci d'urgence (09/10/2026) : l'icône figée au-dessus du jeu, sans icône dans la barre des tâches, ne se fermait plus.
    microInfo: 'Poser une question (Ctrl+Maj+Espace) · clic droit : menu · bloqué : Ctrl+Maj+Retour arrière, deux fois de suite (moins de 2 s) pour quitter',
    micro: 'Poser une question',
    ecoute: 'Je t\'écoute…',
    ouvreLeJeu: e => `${e} : ouvre le jeu puis repose ta question.`,
    microBloque: 'Le micro est bloqué : Paramètres > Confidentialité et sécurité > Microphone, active « Autoriser les applications de bureau à accéder au microphone ».',
    microAbsent: 'Aucun micro trouvé : branche ton casque.',
    microMuet: 'Le micro ne répond pas : vérifie qu’il est branché et qu’aucune autre appli ne l’utilise.',
    rienEntendu: 'Je n\'ai rien entendu.',
    serveurCode: code => `Le serveur du copilote a répondu ${code}.`,
    arreteeEnRoute: 'La réponse s\'est arrêtée en route. Réessaie.',
    voixInterrompue: 'Réponse affichée (voix interrompue)',
    delai: 'Pas de réponse depuis 45 secondes. Réessaie.',
    serveurMuet: 'Le serveur du copilote ne répond pas.',
    repondu: ms => Number.isFinite(ms) ? `Répondu en ${(ms / 1000).toFixed(1).replace('.', ',')} s` : 'Répondu',
    cout: c => `${c.toFixed(1).replace('.', ',')} ${c >= 2 ? 'cents' : 'cent'}`,
    erreurInconnue: 'Erreur inconnue.',
    probleme: 'Problème : voir le panneau',
    oubliee: 'Conversation oubliée',
    raccourciAucun: 'Raccourci indisponible : clique sur l’icône',
    raccourciGlobal: base => `${base} (raccourci en bascule seulement)`,
    pretVersion: v => `Prêt · CK3 ${v || ''}`.trim(),
    pretDemo: 'Prêt · CK3 1.20.0.4 (démo)',
    cerveauIndisponible: 'Cerveau indisponible',
    aucuneCle: 'Aucune clé d\'IA trouvée',
    ck3Absent: 'CK3 n\'est pas lancé',
    // Aide Windows (PowerShell de capture) qui ne répond pas (10/10/2026) : distinct de « CK3 n'est pas lancé ».
    aideEnPanne: 'Aide Windows en panne : capture impossible',
    injoignable: 'Serveur du copilote injoignable',
    voixEnCours: 'Je te le dis à voix haute…',
    // Démonstration (?demo=1) : mêmes étapes que le vrai cerveau.
    demoQuestion: 'Comment je fabrique un hameçon sur mon vassal ?',
    demoReponse: 'Démonstration : pour obtenir un **Hook** (moyen de pression) sur ton vassal, passe par un complot.\n'
      + '1. Fais un clic droit sur son portrait.\n2. Choisis **Fabricate Hook** (fabriquer un moyen de pression).\n'
      + '3. Regarde la **Success Chance** (chance de réussite) avant de valider.\n4. Mets ton **Spymaster** (maître espion) sur sa cour pour aller plus vite.',
    demoEtapes: [['capture', 'Je regarde ton écran…'], ['ecoute', 'J\'écoute ta question…'], ['reflexion', 'Je réfléchis…'], ['recherche', 'Je vérifie sur Internet…']],
    demoErreur: 'CK3 n\'est pas lancé : ouvre le jeu puis repose ta question.',
  },
  en: {
    nom: 'CK3 Copilot',
    panneau: 'Copilot answer',
    attente: 'Looking at your screen…',
    sources: 'Sources',
    suggestions: 'Google search suggestions',
    deplacer: 'Drag the panel to move it: it will stay there · right-click: collapse, reload or quit',
    pret: 'Ready',
    repeter: 'Replay the voice',
    voix: 'Voice',
    voixOn: 'Voice on (click to mute)',
    voixOff: 'Voice off (click to turn it on)',
    nouvelle: 'New question',
    reduireInfo: 'Minimize (the answer is kept: click the icon to reopen it)',
    reduire: 'Minimize and keep the answer',
    fermer: 'Close',
    microInfo: 'Ask a question (Ctrl+Shift+Space) · right-click: menu · stuck: Ctrl+Shift+Backspace, twice within 2 s to quit',
    micro: 'Ask a question',
    ecoute: 'Listening…',
    ouvreLeJeu: e => `${e}: open the game, then ask your question again.`,
    microBloque: 'The microphone is blocked: Settings > Privacy & security > Microphone, turn on “Let desktop apps access your microphone”.',
    microAbsent: 'No microphone found: plug in your headset.',
    microMuet: 'The microphone is not responding: check that it is plugged in and that no other app is using it.',
    rienEntendu: 'I didn’t hear anything.',
    serveurCode: code => `The copilot’s server answered ${code}.`,
    arreteeEnRoute: 'The answer stopped halfway. Try again.',
    voixInterrompue: 'Answer shown (voice interrupted)',
    delai: 'No answer for 45 seconds. Try again.',
    serveurMuet: 'The copilot’s server is not responding.',
    repondu: ms => Number.isFinite(ms) ? `Answered in ${(ms / 1000).toFixed(1)} s` : 'Answered',
    cout: c => `${c.toFixed(1)} ${c.toFixed(1) === '1.0' ? 'cent' : 'cents'}`,
    erreurInconnue: 'Unknown error.',
    probleme: 'Problem: see the panel',
    oubliee: 'Conversation forgotten',
    raccourciAucun: 'Shortcut unavailable: click the icon',
    raccourciGlobal: base => `${base} (shortcut toggles only)`,
    pretVersion: v => `Ready · CK3 ${v || ''}`.trim(),
    pretDemo: 'Ready · CK3 1.20.0.4 (demo)',
    cerveauIndisponible: 'Brain unavailable',
    aucuneCle: 'No AI key found',
    ck3Absent: 'CK3 isn’t running',
    aideEnPanne: 'Windows helper down: capture unavailable',
    injoignable: 'Copilot server unreachable',
    voixEnCours: 'Reading the answer to you…',
    demoQuestion: 'How do I fabricate a hook on my vassal?',
    demoReponse: 'Demo: to get a **Hook** on your vassal, use a scheme.\n'
      + '1. Right-click their portrait.\n2. Choose **Fabricate Hook**.\n'
      + '3. Check the **Success Chance** before you confirm.\n4. Send your **Spymaster** to their court to speed it up.',
    demoEtapes: [['capture', 'Looking at your screen…'], ['ecoute', 'Listening to your question…'], ['reflexion', 'Thinking…'], ['recherche', 'Checking online…']],
    demoErreur: 'CK3 isn’t running: open the game, then ask your question again.',
  },
};
